name: PlayerPotions
main: gg.solarmc.playerpotions.PlayerPotions
version: ${project.version}
authors: [ zone_infinity ]
commands:
  ppotion:
    description: The only command of Player Potions
    usage: /<command>